### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by whentheis** [9NLK7/93qjoadnlaknwldk#1]
![image](https://user-images.githubusercontent.com/83487049/148181398-167f0c11-8279-4784-b36d-1f57c44df423.png)
Everytime i execute the script, this always pops in the console, and nothing happens, no gui no anything

I'm using KRNL for my executor

**Comment by 9NLK7** [comment]
krnl moment
get synapse

**Comment by whentheis** [comment]
nvm now it works
